"""Added Video model

Revision ID: 4a94c64c39ef
Revises: fdacb5cd3048
Create Date: 2024-09-23 18:33:03.089444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4a94c64c39ef'
down_revision: Union[str, None] = 'fdacb5cd3048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'videos',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('name', sa.String, index=True),
        sa.Column('size', sa.Integer),
        sa.Column('path', sa.String),
        sa.Column('converted', sa.String, default="Pending"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
