"""adding Videos model

Revision ID: 4dd8f36bcc13
Revises: 54698ee387df
Create Date: 2024-09-23 13:44:35.725259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd8f36bcc13'
down_revision: Union[str, None] = '54698ee387df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'videos',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('name', sa.String, index=True),
        sa.Column('size', sa.Integer),
        sa.Column('path', sa.String),
        sa.Column('converted', sa.String, default="Pending"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
